  backend:
  name: github
  repo: myproxynetwork/my-knowledge-base
  branch: main
  auth_type: implicit
  app_id: <Ov23liyrcFGHuoQ2clmp>
  site_url: http://80.240.20.135
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "docs"
    label: "Документация"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Тело документа", name: "body", widget: "markdown" }